# Generated by Django 2.2 on 2019-12-22 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='About me')),
                ('resumeLink', models.URLField(max_length=1000)),
            ],
            options={
                'verbose_name': 'About Me',
                'verbose_name_plural': 'About Me',
            },
        ),
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipAddress', models.CharField(max_length=20)),
                ('fname', models.CharField(max_length=200)),
                ('lname', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=300)),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name': 'Messages',
                'verbose_name_plural': 'Messages',
            },
        ),
        migrations.CreateModel(
            name='educationalEx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('org', models.CharField(max_length=150)),
                ('time', models.CharField(max_length=20)),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'Educational Experience',
                'verbose_name_plural': 'Educational Experience',
            },
        ),
        migrations.CreateModel(
            name='featuredPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='featuredPost')),
                ('heading', models.CharField(max_length=200)),
                ('postMetaDetail', models.CharField(max_length=100)),
                ('postDetail', models.CharField(max_length=300)),
                ('link', models.URLField(max_length=500)),
            ],
            options={
                'verbose_name': 'Featured Post',
                'verbose_name_plural': 'Featured Post',
            },
        ),
        migrations.CreateModel(
            name='mySkills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'My Skills',
                'verbose_name_plural': 'My Skills',
            },
        ),
        migrations.CreateModel(
            name='profEx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('org', models.CharField(max_length=150)),
                ('orgLink', models.URLField(max_length=300)),
                ('time', models.CharField(max_length=30)),
                ('work', models.TextField()),
            ],
            options={
                'verbose_name': 'Professtional Experience',
                'verbose_name_plural': 'Professtional Experience',
            },
        ),
        migrations.CreateModel(
            name='ProfSkills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=100)),
                ('percentage', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Professional Skills',
                'verbose_name_plural': 'Professional Skills',
            },
        ),
        migrations.CreateModel(
            name='TechSkills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=100)),
                ('percentage', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Technical Skills',
                'verbose_name_plural': 'Technical Skills',
            },
        ),
        migrations.CreateModel(
            name='testimonials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='testimonial_photos')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonial',
            },
        ),
        migrations.CreateModel(
            name='whatIDo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100)),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'What I Do',
                'verbose_name_plural': 'What I Do',
            },
        ),
        migrations.AlterModelOptions(
            name='personalinformation',
            options={'verbose_name': 'Personal Information', 'verbose_name_plural': 'Personal Information'},
        ),
    ]
