# Generated by Django 2.2 on 2019-12-22 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191222_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationalex',
            name='time',
            field=models.CharField(max_length=50),
        ),
    ]
