# Generated by Django 2.2 on 2020-01-08 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20191222_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='ipAddress',
        ),
    ]
